---
version: 2
updates:
  - package-ecosystem: "gradle"
    open-pull-requests-limit: 10
    directory: "."
    groups:
      third-party:
        patterns:
          - "*"
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
